# Generated by Django 5.2.5 on 2025-08-29 19:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Restraunt",
            fields=[
                (
                    "camis",
                    models.CharField(max_length=10, primary_key=True, serialize=False),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "boro",
                    models.CharField(
                        choices=[
                            ("Manhattan", "Manhattan"),
                            ("Bronx", "Bronx"),
                            ("Brooklyn", "Brooklyn"),
                            ("Queens", "Queens"),
                            ("Staten Island", "Staten Island"),
                        ],
                        max_length=20,
                    ),
                ),
                ("building", models.CharField(max_length=20)),
                ("street", models.CharField(max_length=255)),
                ("zipcode", models.CharField(blank=True, max_length=10, null=True)),
                ("phone", models.CharField(blank=True, max_length=20, null=True)),
                ("cuisine", models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Inspection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("inspection_date", models.DateField()),
                ("inspection_type", models.CharField(max_length=50)),
                ("action", models.CharField(max_length=255)),
                ("score", models.IntegerField(blank=True, null=True)),
                ("grade", models.CharField(blank=True, max_length=2, null=True)),
                ("grade_date", models.DateField(blank=True, null=True)),
                (
                    "restraunt",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="inspections",
                        to="api.restraunt",
                    ),
                ),
            ],
            options={
                "ordering": ["-inspection_date"],
                "get_latest_by": "inspection_date",
            },
        ),
        migrations.CreateModel(
            name="Violation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(blank=True, max_length=20, null=True)),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "critical_flag",
                    models.CharField(
                        choices=[
                            ("Critical", "Critical"),
                            ("Not Critical", "Not Critical"),
                            ("Not Applicable", "Not Applicable"),
                        ],
                        default="Not Applicable",
                        max_length=20,
                    ),
                ),
                (
                    "inspection",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="violations",
                        to="api.inspection",
                    ),
                ),
            ],
        ),
    ]
